name: GitHub Pages Pelican Build Action
description: Build a Pelican site via UV/Pelican and deploy it to GitHub Pages.
branding:
  icon: home
  color: red

inputs:
  GH_PAGES_BRANCH:
    description: 'Deployment branch (defaults to gh-pages)'
    required: false
    default: 'gh-pages'
  GH_PAGES_CNAME:
    description: 'Custom domain for CNAME (omit or set to "none" if none)'
    required: false
    default: 'none'
  PELICAN_CONFIG_FILE:
    description: 'Pelican config file'
    required: false
    default: 'pelicanconf.py'
  PELICAN_CONTENT_FOLDER:
    description: 'Pelican content folder'
    required: false
    default: 'content'

runs:
  using: 'docker'
  image: 'Dockerfile'