[project]
name = "macuyiko-github-io"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "markdown>=3.8",
    "pelican>=4.11.0",
    "smartypants>=2.0.1",
    "typogrify>=2.1.0",
]
